language: generic
dist: trusty
script:
  - chmod +x ./_build/deploy.sh
  - chmod +x ./_build/build.sh
  - ./_build/build.sh
  - ./_build/deploy.sh > /dev/null
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=helloworld
